### ISSUE TITLE
stack-pr list fails with "Not a valid object name origin/main"

### ISSUE THREAD

**Issue by zaro0508** [modularml/stack-pr#46]
I think this is because my default branch is named `master` instead of `main`?  Is there a workaround besides maybe changing my default branch to `main`?

```
(s3-synapse-sync) ➜  s3-synapse-sync git:(update-python1) git remote -v
origin	git@github.com:zaro0508/s3-synapse-sync.git (fetch)
origin	git@github.com:zaro0508/s3-synapse-sync.git (push)
upstream	git@github.com:Sage-Bionetworks/s3-synapse-sync.git (fetch)
upstream	git@github.com:Sage-Bionetworks/s3-synapse-sync.git (push)
```

from `master` branch i do `git checkout -b update-python1`

```
(s3-synapse-sync) ➜  s3-synapse-sync git:(update-python1) git log -1
commit 4892e252c5e684c01915eebeb866a93fd404700e (HEAD -> update-python1)
Author: Khai Do <zaro0508@gmail.com>
Date:   Thu Oct 24 16:29:03 2024 -0700

    [IT-3817] update python version

    Python 3.8 has been deprecated, updating to python 3.11
```

```
(s3-synapse-sync) ➜  s3-synapse-sync git:(update-python1) stack-pr view
Exitcode: 128
Stdout: None
Stderr: fatal: Not a valid object name origin/main

Traceback (most recent call last):
  File "/Users/zaro0508/.local/bin/stack-pr", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/zaro0508/.local/pipx/venvs/stack-pr/lib/python3.13/site-packages/stack_pr/cli.py", line 1398, in main
    common_args = deduce_base(common_args)
  File "/Users/zaro0508/.local/pipx/venvs/stack-pr/lib/python3.13/site-packages/stack_pr/cli.py", line 840, in deduce_base
    deduced_base = get_command_output(
        ["git", "merge-base", args.head, f"{args.remote}/{args.target}"]
    )
  File "/Users/zaro0508/.local/pipx/venvs/stack-pr/lib/python3.13/site-packages/stack_pr/shell_commands.py", line 63, in get_command_output
    proc = run_shell_command(cmd, capture_output=True, quiet=False, **kwargs)
  File "/Users/zaro0508/.local/pipx/venvs/stack-pr/lib/python3.13/site-packages/stack_pr/shell_commands.py", line 42, in run_shell_command
    return subprocess.run(list(map(str, cmd)), **kwargs)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'merge-base', 'HEAD', 'origin/main']' returned non-zero exit status 128.
```

**Comment by ZolotukhinM** [comment]
You can specify the name of your branch using `-T/--target` command line option. Also you can put it into a config file so that you don't need to do that every time time (see [docs](https://github.com/modularml/stack-pr/blob/main/README.md#config-files) about using config files).

**Comment by ZolotukhinM** [comment]
I'll close this issue for now - please re-open or file new ones if you have more questions!

**Comment by johnfn** [comment]
Why would you close this issue? This is an obvious crash - you could easily log a clearer message
